### PR TITLE
Raise exception if a playbook fails execution

### PR DESCRIPTION
**Pull request by mkanoor**
1. A user can supress the exception by setting ignore_errors
2. Fixed tests where the playbook was failing during execution
3. Added tests for ignore_errors

### CODE REVIEW

**Comment by mkanoor** [comment]
@benthomasson Please review

**Review by benthomasson — CHANGES_REQUESTED** [review]
I am not sure that raising an exception is the right thing to do on a failing playbook.   We should generate a new out going event that describes the failure so that the UI can update the database about the failure.

**Comment by benthomasson** [comment]
@mkanoor this needs rebasing.

**Comment by mkanoor** [comment]
Closed in favor of #132

**Pull request closed without merging**
